name: Load Performance Test

on:
  push:
    branches:
      - main
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  performance-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install exceljs

      - name: Run Performance Tests
        run: node performance_tests/run_performance_tests.js

      - name: Upload Performance Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: queueless-performance-reports
          path: android-performance-reports/
          retention-days: 7
